# Generated by Django 2.0.4 on 2018-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
