# Generated by Django 2.0.4 on 2018-04-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
