# Generated by Django 2.0.4 on 2018-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0004_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
