# Generated by Django 2.0.4 on 2018-04-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0005_auto_20180425_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='file',
        ),
    ]
