# Generated by Django 2.0.4 on 2018-04-28 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0007_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
